name: Teste Antes Territorial

on:
  pull_request:

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install pandas
      - name: Teste territorial atual
        working-directory: algoritimos
        run: python teste_territorial.py
